spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      eclipselink.logging.level: WARNING
#     loadtime-weaving is enabled when finding the use of -javaagent:lib/spring-instrument.jar
#     weaving details can be customized here:
      eclipselink.weaving.rest: false

logging:
  level:
    root: WARN

  datasource:
    platform: h2
    url: "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false"
    username: sa
    password:

  h2:
    console:
      enabled: true